{"uid":"6697f56e91eb7c69","name":"test_view_contact_incorrect_authorization","fullName":"test.Contactos.test_view_contact#test_view_contact_incorrect_authorization","historyId":"d91fa7ae39053853894ed5fd9da1ac35","time":{"start":1726762239910,"stop":1726762239911,"duration":1},"status":"broken","statusMessage":"TypeError: list indices must be integers or slices, not str","statusTrace":"setup_contact_view_contact = ({'Espo-Authorization': 'YWRtaW46ODAwNDkwNTM=', 'X-Api-Key': '4c29fe9482f3bccb7ac0a7d04015a2e7'}, [{'accountId': None, 'accountIsInactive': None, 'accountName': None, 'accountType': None, ...}])\nget_headers = <function get_headers.<locals>._get_headers at 0x7f8c24b5be20>\n\n    @pytest.mark.regression\n    @pytest.mark.functional\n    def test_view_contact_incorrect_authorization(setup_contact_view_contact,get_headers):\n        headers, contact = setup_contact_view_contact\n        headersInvalid = Auth().get_invalid_user_headers(get_headers)\n>       response = EspocrmRequest().get(EndpointContacts.view(contact['id']), headersInvalid)\nE       TypeError: list indices must be integers or slices, not str\n\ntest/Contactos/test_view_contact.py:42: TypeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"get_headers","time":{"start":1726762227223,"stop":1726762227224,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_contact_view_contact","time":{"start":1726762239728,"stop":1726762239910,"duration":182},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"afterStages":[{"name":"setup_contact_view_contact::0","time":{"start":1726762239913,"stop":1726762239913,"duration":0},"status":"broken","statusMessage":"TypeError: list indices must be integers or slices, not str\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"/home/runner/work/espo-automation-final/espo-automation-final/test/Contactos/conftest.py\", line 82, in setup_contact_view_contact\n    ContactCall().delete(headers, contact['id'])\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"labels":[{"name":"tag","value":"functional"},{"name":"tag","value":"regression"},{"name":"parentSuite","value":"test.Contactos"},{"name":"suite","value":"test_view_contact"},{"name":"host","value":"fv-az1116-0"},{"name":"thread","value":"2157-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.Contactos.test_view_contact"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["functional","regression"]},"source":"6697f56e91eb7c69.json","parameterValues":[]}