{"uid":"eddbb2eb13c03e20","name":"test_list_contacts_offset_negative","fullName":"test.Contactos.test_list_contacts#test_list_contacts_offset_negative","historyId":"4aed93653ed61b3c5c00568d6e6c31e2","time":{"start":1726762240826,"stop":1726762241023,"duration":197},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError","statusTrace":"setup_teardown_list_contacts = ({'Espo-Authorization': 'YWRtaW46ODAwNDkwNTM=', 'X-Api-Key': '4c29fe9482f3bccb7ac0a7d04015a2e7'}, {'accountIsInactive'...'accountsIds': [], ...}, {'accountId': None, 'accountIsInactive': None, 'accountName': None, 'accountType': None, ...})\n\n    @pytest.mark.regression\n    @pytest.mark.functional\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\", condition=True)\n    def test_list_contacts_offset_negative(setup_teardown_list_contacts):\n        headers, contact1, contact2 = setup_teardown_list_contacts\n        response = EspocrmRequest().get(EndpointContacts.list(offset=-1), headers)\n>       AssertionStatusCode().assert_status_code_400(response)\n\ntest/Contactos/test_list_contacts.py:145: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>\n\n    @staticmethod\n    def assert_status_code_400(response):\n>       assert response.status_code == 400\nE       AssertionError\n\nsrc/assertions/status_code_assertions.py:19: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"get_headers","time":{"start":1726762231405,"stop":1726762231405,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_teardown_list_contacts","time":{"start":1726762237712,"stop":1726762238113,"duration":401},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"afterStages":[{"name":"setup_teardown_list_contacts::0","time":{"start":1726762241379,"stop":1726762241729,"duration":350},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"functional"},{"name":"tag","value":"regression"},{"name":"parentSuite","value":"test.Contactos"},{"name":"suite","value":"test_list_contacts"},{"name":"host","value":"fv-az529-703"},{"name":"thread","value":"2160-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.Contactos.test_list_contacts"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["functional","regression","@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"]},"source":"eddbb2eb13c03e20.json","parameterValues":[]}